### ISSUE TITLE
Błąd przy pobieraniu statusu płatności 

### ISSUE THREAD

**Issue by b4after-pl** [pay-now/paynow-php-sdk#17]
Przy próbie pobrania statusu płatności dostaję błąd:

`Fatal error: Uncaught Paynow\Exception\PaynowException: Error occurred during processing request in D:\Bank danych\Projekty WWW\Payments\vendor\pay-now\paynow-php-sdk\src\Paynow\Service\Payment.php on line 53`

Mój kod poniżej:

```
require __DIR__ . '/vendor/autoload.php';
if(isset($_GET['paymentId']) && isset($_GET['paymentStatus'])) {

	$client = new \Paynow\Client('XXX', 'XXX', 'sandbox');
	try {
		$paymentID = $_GET['paymentId'];
		
		$payment = new \Paynow\Service\Payment($client);
		$result = $payment->status($paymentID);
		var_dump($result);
	} catch (PaynowException $exception) {
	   var_dump($exception->getErrors());
	}
}
```
Klucze i sygnatury są prawidłowe.

**Comment by emilleszczak2** [comment]
@b4after-pl Napisz do nas na support@paynow.pl. W wiadomości podaj również numer paymentId.

**Comment by b4after-pl** [comment]
Poszło.
