### ISSUE TITLE
Missing option to override notification url

### ISSUE THREAD

**Issue by amodliszewski** [pay-now/paynow-php-sdk#23]
API should allow to override notification url set in panel, same as it allows to override return_url

It would simplify clients workflow in end applications - there would be no need to instruct user to put in proper notification url in panel.

**Comment by emilleszczak2** [comment]
@amodliszewski That option is available in SDK. Please look at the `ShopConfiguration` service.

**Comment by amodliszewski** [comment]
@emilleszczak2 Please add some docs in OpenAPI specs and/or here, this option is not documented anywhere
