### ISSUE TITLE
Wdrożenie płatności formularz danych POST

### ISSUE THREAD

**Issue by http200it** [pay-now/paynow-php-sdk#35]
### Wdrożenie płatności.

Witam mam problem z koncepcja Państwa płatności, a support@paynow.pl niestety NIE RACZY opowiadać!

Zatem o co mi chodzi -  W systemie przeley24, PayPal itd... w celu zainicjowania płatności = obsłużenia wysyłamy dane POST z  formularza w którym may klienta, za co płaci, cenę itd...
```
<form action="https://sandbox.przelewy24.pl/trnDirect" method="post" class="form" id="formplatonline">
<input type="text" name="p24_session_id" value="<?php echo $p24_session_id;?>">
<input type="text" name="p24_merchant_id" value="<?php echo $p24_merchant_id;?>">
<input type="text" name="p24_pos_id" value="<?php echo $p24_merchant_id;?>">
<input type="text" name="p24_amount" value="<?php echo $p24_amount;?>">
ITD....
<input type="submit" value="go" />
</form>
```

ITD.... Wysłanie formularza przenosi do systemu transakcyjnego na  stronę wyboru banku itd...

Drugim etapem jest mechanizm odbioru płatności ale to się dzieje w tle.

**Wiec pytanie brzmi jak to samo zrealizować u Was paynow.pl** ?
W dokumentacji nie znajduje nic o analogicznym formularzu ?

**Comment by michalskladanowski** [comment]
Dzień dobry,
na chwilę obecną nie posiadamy możlwiości inicjacji płatności bezpośrednio z formularza. Dane z formularza należy przekazać do backendu i odpowiednio sformułowaną wiadomość przesłać do API.
Proszę również o infromację z jakiego adresu kontaktował się Pan z naszym supportem, gdyż nie mogę znaleźć Pana wiadomości.

**Comment by http200it** [comment]
Efektem końcowym  jest przejście ze strony zamówienia > na stronę systemu transakcyjnego. 
https://i.ibb.co/tPgCRxn/screen-paynow.jpg

Z tego co widziałem w sklepie testowym będzie URL
`https://paywall.paynow.pl/NOXN-O0T-7YG-8QV?token=**JAKIS-TOKEN**`

Wiec pytanie brzmi jak wygenerować ten **JAKIS-TOKEN**?  Bo rozumiem, ze tak to działa ? 

Kontowałem się z innego niż ten na githubie. Zgłoszenie "obsługiwała" osoba 

Marta Myh* <jira@me* .atlassian.net>
Z pozdrowieniami
Zespół Paynow

**Comment by http200it** [comment]
Panie Michale **Dziękuję** za odpowiedz na e-mail -> Pozdrawiam
