### ISSUE TITLE
Poprawka w dokumentacji notyfikacji

### ISSUE THREAD

**Issue by pusty44** [pay-now/paynow-php-sdk#50]
W README mamy opisane jak używać notyfikacji przy pomocy SDK, ale w dokumentacji nie ma nawet słowa co taka notyfikacja zwraca, w jakim formacie itd. Jest tylko opisane jak zmienić adres do notyfikacji.

**Comment by michalskladanowski** [comment]
w sekcji [Make payment](https://docs.paynow.pl/#section/Payments/Make-a-payment) w kroku 8 przedstawiony jest przykład powiadomienia dla statusu CONFIRMED 
![image](https://user-images.githubusercontent.com/59174285/127001027-b64c5597-40b2-4ac6-8aaa-c4b2a388a773.png)

**Comment by emilleszczak2** [comment]
Dodaliśmy sekcje `Notifications` w menu `Integration`
