### ISSUE TITLE
Integracja z Omnipay

### ISSUE THREAD

**Issue by pszalko** [pay-now/paynow-php-sdk#51]
Czy jest w planach integracja z biblioteką Omnipay?

**Comment by emilleszczak2** [comment]
@pszalko dzięki za sugestię. 

Uwzględnimy to w naszych planach.

**Comment by pszalko** [comment]
@emilleszczak2 Dziękuję za szybką odpowiedź.
Proszę jeszcze o informację kiedy można spodziewać się tej integracji? 
Pytam, ponieważ mamy dwa projekty które czekają na wdrożenie pay-now + omnipay i właśnie decydujemy czy robić swoją implementację, czy możemy jeszcze poczekać na oficjalną.

**Comment by emilleszczak2** [comment]
@pszalko Na dzień dzisiejszy nie znam konkretnej daty, ale będzie to szybciej niż w sierpniu.

**Comment by pszalko** [comment]
@emilleszczak2 Super! Taka odpowiedź mi wystarczy :) Proszę o powiadomienie w tym wątku jak implementacja będzie już gotowa.

**Comment by pszalko** [comment]
@emilleszczak2 Udało się wykonać implementację pay-now dla Omnipay?

**Comment by emilleszczak2** [comment]
Niestety prace się jeszcze nie rozpoczęły. Obstawiam drugą połowę miesiąca.

**Comment by pszalko** [comment]
@emilleszczak2 Udało się wystartować prace z Omnipay?

**Comment by piotrfilipek** [comment]
@emilleszczak2 @pszalko Aktualnie ja prowadzę pracę nad integracją z Omnipay :)

**Comment by emilleszczak2** [comment]
Udostępniliśmy integrację z Omnipay tutaj: https://github.com/pay-now/omnipay-paynow

**Comment by pszalko** [comment]
Dziękuję! :)

**Comment by piotrfilipek** [comment]
Również dziękuję. Nie muszę już rozwijać swojego drivera do Omnipay. mBank najlepszym bankiem w Polsce :)
Temat chyba można zamknąć.
