### ISSUE TITLE
Kwoty z groszami

### ISSUE THREAD

**Issue by faran22** [pay-now/paynow-php-sdk#60]
Gdy podaje amount zawierający grosze to nie działa. Bardzo proszę o pomoc.
Podaje kwotę: 101.21 
$exception->getErrors() zwraca błąd:
[0] => Paynow\Exception\Error Object
        (
            [type:Paynow\Exception\Error:private] => VALIDATION_ERROR
            [message:Paynow\Exception\Error:private] => amount: invalid numeric value: 101.2099999999999937472239253111183643341064453125
        )

**Comment by emilleszczak2** [comment]
Kwota musi być wyrażona w najmniejszej jednostce, dla PLN jest to 1 grosz. Czyli 1 zł to wartość 100.
